import type { Quiz } from '@types/index';

/**
 * Mock quiz data for development and demonstration
 */
export const mockQuizzes: Quiz[] = [
  {
    id: '1',
    title: 'World Geography Master',
    description: 'Test your knowledge of countries, capitals, and landmarks around the world.',
    category: 'trivia',
    difficulty: 'medium',
    questionsCount: 20,
    estimatedTime: 10,
    image: 'https://images.unsplash.com/photo-1526778548025-fa2f459cd5c1?w=800&h=600&fit=crop',
    tags: ['geography', 'world', 'capitals'],
    plays: 45230,
    rating: 4.8,
    featured: true,
  },
  {
    id: '2',
    title: 'Logic Puzzles Pro',
    description: 'Challenge your mind with advanced logic puzzles and brain teasers.',
    category: 'logic',
    difficulty: 'hard',
    questionsCount: 15,
    estimatedTime: 20,
    image: 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800&h=600&fit=crop',
    tags: ['logic', 'puzzles', 'brain-teasers'],
    plays: 32150,
    rating: 4.9,
    featured: true,
  },
  {
    id: '3',
    title: 'Math Wizardry',
    description: 'Sharpen your mathematical skills with fun and challenging problems.',
    category: 'math',
    difficulty: 'easy',
    questionsCount: 25,
    estimatedTime: 15,
    image: 'https://images.unsplash.com/photo-1509228627152-72ae9ae6848d?w=800&h=600&fit=crop',
    tags: ['math', 'arithmetic', 'problem-solving'],
    plays: 58720,
    rating: 4.6,
  },
  {
    id: '4',
    title: 'Classic Riddles Collection',
    description: 'Can you solve these timeless riddles and brainteasers?',
    category: 'riddles',
    difficulty: 'medium',
    questionsCount: 30,
    estimatedTime: 12,
    image: 'https://images.unsplash.com/photo-1516339901601-2e1b62dc0c45?w=800&h=600&fit=crop',
    tags: ['riddles', 'mystery', 'thinking'],
    plays: 41890,
    rating: 4.7,
    featured: true,
  },
  {
    id: '5',
    title: 'Daily Sudoku Challenge',
    description: 'Complete today\'s sudoku puzzle and improve your number skills.',
    category: 'sudoku',
    difficulty: 'medium',
    questionsCount: 1,
    estimatedTime: 25,
    image: 'https://images.unsplash.com/photo-1611996575749-79a3a250f948?w=800&h=600&fit=crop',
    tags: ['sudoku', 'numbers', 'daily'],
    plays: 67340,
    rating: 4.5,
  },
  {
    id: '6',
    title: 'Movie Trivia Mania',
    description: 'How well do you know your favorite films? Find out here!',
    category: 'trivia',
    difficulty: 'easy',
    questionsCount: 20,
    estimatedTime: 8,
    image: 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=800&h=600&fit=crop',
    tags: ['movies', 'entertainment', 'pop-culture'],
    plays: 73210,
    rating: 4.8,
  },
  {
    id: '7',
    title: 'Word Master Challenge',
    description: 'Expand your vocabulary with this word-based quiz.',
    category: 'word-games',
    difficulty: 'hard',
    questionsCount: 40,
    estimatedTime: 18,
    image: 'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=800&h=600&fit=crop',
    tags: ['words', 'vocabulary', 'language'],
    plays: 29450,
    rating: 4.9,
  },
  {
    id: '8',
    title: 'Memory Match Extreme',
    description: 'Test your memory with increasingly difficult patterns.',
    category: 'memory',
    difficulty: 'expert',
    questionsCount: 10,
    estimatedTime: 30,
    image: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=800&h=600&fit=crop',
    tags: ['memory', 'patterns', 'concentration'],
    plays: 18920,
    rating: 4.7,
    featured: true,
  },
];
